/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pandacoder_ndkexample_NdkImageProcessor_ImageProcessor */

#ifndef _IMAGE_PROCESSOR_H_
#define _IMAGE_PROCESSOR_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pandacoder_ndkexample_NdkImageProcessor_ImageProcessor
 * Method:    AdjustImageBrightness
 */
JNIEXPORT void JNICALL Java_com_pandacoder_ndkexample_NdkImageProcessor_ImageProcessor_AdjustImageBrightnessNDK
  (JNIEnv *, jclass, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
